### ISSUE TITLE
Catch method signature

### ISSUE THREAD

**Issue by fredrikekelund** [pyrsmk/qwest#100]
The order of arguments passed to a promise chain's `catch` handler doesn't match the common practice of providing the error as the first argument. This causes issues when another error is thrown as part of the promise chain, since what would have been my `xhr` argument suddenly becomes the error instead. I think it would be a good idea to provide arguments to the catch handler in the order `error, xhr, response`, this would result in more consistent behavior.

Thanks for a really nice library!

**Comment by pyrsmk** [comment]
If I understand well, the problem is that when an error is thrown inside a `then` callback then the `catch` callback catches the error but with the wrong parameters? (which is normal)

In that case, shouldn't it be better to catch your errors with a normal `try-catch` block? Moving arguments seems a good idea, but there's not retro-compatibility at all with the current use of the library.

**Comment by fredrikekelund** [comment]
Yep, that's exactly right!

Well, not all errors can be foreseen (this was how I encountered this problem), so the developer won't be able to catch all errors by adding try/catch blocks. And since error handling is a core feature of promises, and promises are native to modern browsers, interoperability between implementations seems especially important.

I realize that this is a breaking change, but I definitely think it's important enough to warrant it

**Comment by pyrsmk** [comment]
I think so... You're right, it's better to have a common implementation. I'm fixing this right away and add a note on the docs for that modification.

**Comment by fredrikekelund** [comment]
Cool 👍 Probably appropriate to bump the major version number as well to prevent breakage

**Comment by pyrsmk** [comment]
Normally, the minor version number should be good enough, isn't it? NPM seems to not update a library if the minor number changes (by default).

**Comment by fredrikekelund** [comment]
Well, generally any incompatible API changes should bump the major version number. Seems silly in a way for such a small change, but if people rely on the current behavior, then it would be a shame if their apps unexpectedly broke

**Comment by pyrsmk** [comment]
But, maybe I'm wrong, in a web app we don't update libraries otherwise we need too because of a bug or something. And if we update the whole thing, we take a look at the current documentation. Yeah, it seems a bit silly to bump to `3.0.0` although the code has not change at all :p

**Comment by pyrsmk** [comment]
Furthermore, we don't push the project in production without tests :p

**Comment by fredrikekelund** [comment]
Agreed that ideally there are tests, but maybe there aren't any. And maybe I've just recently cloned a project and I'm running `npm install` and things aren't working as expected when running the app. Or maybe I have 25 dependencies and I'm running `npm update` because I need the latest version of a single one. Maybe people have implemented some kind of retry strategy for the request in their catch handler, and they're working with the XHR object somehow and suddenly the XHR is an error instead :/

In any case, I would recommend bumping the major version number. I know the semver rules are supposed to be more like guidelines than absolute law, but they're pretty clear about the backwards compatibility stuff http://semver.org/

**Comment by pyrsmk** [comment]
Anyway! I cross my fingers and bump to `2.3`...

**Comment by pyrsmk** [comment]
You're right. Fuck. Ok, let's do it ^^

**Comment by fredrikekelund** [comment]
Good call! :) Thanks for the quick reply btw
