### ISSUE TITLE
"Error while parsing JSON body" with "responseType: 'auto'" if No Content is successfully returned

### ISSUE THREAD

**Issue by sheymann** [pyrsmk/qwest#102]
Hello,

If the sucess response of a GET method is

> HTTP/1.1 204 No Content

Qwest throws the following exception:

> Error while parsing JSON body : SyntaxError: Unexpected end of input 

Example code:

```js
var url = 'http://crunchbase.linkurio.us/api/auth/logout';

qwest.get(url, null, {
  cache: true,
  responseType: 'auto'
})
.catch(function(e) { throw e; });
```

**Comment by pyrsmk** [comment]
I'll investigate this ASAP ;)

**Comment by pyrsmk** [comment]
Fixed withe next release
