### ISSUE TITLE
Preparse function for response.body

### ISSUE THREAD

**Issue by planttheidea** [pyrsmk/qwest#103]
This library looks badass, and I was hoping to leverage it on a project, however we have a prefix we add to the front of our JSON that needs to be stripped out prior to parsing. Is there a way to work with the responseText prior to the JSON parsing? In jQuery's ajax implementation they have a dataFilter function in the ajaxPrefilters that performs this.

**Comment by pyrsmk** [comment]
I'll take a look to this and tell you what we can do ;)

**Comment by planttheidea** [comment]
Sweet, thanks!

**Comment by pyrsmk** [comment]
I think you can achieve it by setting `responseType` to `text` so you'll have raw output and then you can parse the JSON by hand ;)

PS : sorry for the late answer

**Comment by pyrsmk** [comment]
Closing this because of idling; reopen it if you encounter the same problem
