### ISSUE TITLE
Remove complete() promise

### ISSUE THREAD

**Issue by pyrsmk** [pyrsmk/qwest#105]
Because it's messy by design, then() and catch() have not the same arguments. Furthermore, it's not really needed.

**Comment by phillip-haydon** [comment]
:( @pyrsmk I was using to handle things that must happen in both `.catch` and `.then`

i.e, submit form, then (handle success), catch (handle error), complete (enable form again).

Removal means I have to make enable call twice. :)

**Comment by pyrsmk** [comment]
Is that a big issue? You can make a function and call it in both methods. But I'm open to any better idea than the previous `complete()` implementation. Maybe a better approach like  a `complete()` method without any argument passed...

**Comment by phillip-haydon** [comment]
I've never used the args from `complete`, I'm not fussed, I just upgraded and all my codes broke so I came to see why it was removed :)

Just wanted to throw my 2c in to say I found it useful.

**Comment by pyrsmk** [comment]
If you found it useful I can consider to implement it again. That's not a big problem :p 
Moreover, I've planned a new release for soon.

I just dropped it because it seemed to me that it wasn't really used, but you gave me a good case of its use ;)

**Comment by sunjay** [comment]
What's the suggested alternative to complete()?

**Comment by pyrsmk** [comment]
Throwing up your `complete()` code in an external function, and calling it in `then()` and `catch()`. But it's not really interesting. I'll restore `complete()` today since you seem to need it too. The only thing to note from the previous implementation is that the promise won't be called with arguments anymore like : 

```js
qwest.get(url)
	 .then(function(xhr, response) {
		// blah blah
	 })
	 .complete(function() {
	 	// yay
	 });
```

**Comment by pyrsmk** [comment]
Fixed with latest release

**Comment by sunjay** [comment]
@pyrsmk if you added back complete, you should probably remove the notice from the README:

> complete() has been removed

**Comment by pyrsmk** [comment]
Ah yes, I forgot that, thanks! I should remove the entire paragraph
