### ISSUE TITLE
Why don't use native parse for 'document'?

### ISSUE THREAD

**Issue by lmk123** [pyrsmk/qwest#109]
I found qwest use iframe to parse `document`(see https://github.com/pyrsmk/qwest/blob/master/src/qwest.js#L184-L193), but it will make more HTTP Request like this:

![qwest](https://cloud.githubusercontent.com/assets/5035625/13165617/0e5bc842-d6fa-11e5-8058-c6e36407053d.png)

Why don't use `xhr.responseType = 'document'` to parse it if possible?

Related:
https://github.com/pyrsmk/qwest/blob/master/src/qwest.js#L112
http://caniuse.com/#feat=xhr2

**Comment by pyrsmk** [comment]
I don't know anymore why I'm using iframes, but it should be for the good of us all :p Because I used XHR2 parser at first. If I'm using iframes now it's because some browser didn't support this as expected. I'll watch into the commits if I can find why ^^

**Comment by pyrsmk** [comment]
https://github.com/pyrsmk/qwest/commit/51f6f8bd8a899fc3a45187e22ba13e1946dbaaba

So... The only way to find out why I put an internal routine is to replace the code to use the XHR2 `document` routine and run all the tests on all browsers. But I won't do that :p 

Then... The question is why your request are being aborted? Since they're not documents at all. How's your qwest calls look?

**Comment by lmk123** [comment]
See https://jsfiddle.net/lmk123/bdkqgqtd/

Because qwest use iframes to load document string, so the URI in the document will be load, and when you remove the iframe from `document.body`, these URI request will be aborted.

**Comment by pyrsmk** [comment]
Ok, I see... I'll investigate this a bit and see what it could be done ;)

**Comment by lmk123** [comment]
I found you add this logic since 51f6f8bd8a899fc3a45187e22ba13e1946dbaaba at https://github.com/pyrsmk/qwest/blob/51f6f8bd8a899fc3a45187e22ba13e1946dbaaba/src/qwest.js#L362 , hope be helpful. :smile:

**Comment by pyrsmk** [comment]
Yep, I mentioned this commit in a previous comment ;)
But thanks a lot for helping!

**Comment by pyrsmk** [comment]
Fixed in next release
