### ISSUE TITLE
Would be nice to be able to set base headers for all requests

### ISSUE THREAD

**Issue by rohan-deshpande** [pyrsmk/qwest#110]
Heya thanks for this lib, I'm currently using `qwest` in my React data framework [Trux](http://github.com/rohan-deshpande/trux) and it's quite good! 

One thing I was thinking was it would be nice to be able to set a base headers object that will get used for all requests. The reason for this is if you are integrating the requests with an API of some sort, it becomes troublesome to set the headers for every request with your authorisation header if its required. I guess what I'm proposing is something similar to jQuery's `$.ajaxSetup` method.

**Comment by pyrsmk** [comment]
It's an interesting option to implement! I'm planning it for the next release ;)

**Comment by rohan-deshpande** [comment]
Awesome!

**Comment by rohan-deshpande** [comment]
Also being able to set the `responseType` for all requests would be good too!

**Comment by pyrsmk** [comment]
:+1:

**Comment by pyrsmk** [comment]
Fixed with latest release
