### ISSUE TITLE
Can't bind() promise

### ISSUE THREAD

**Issue by roblav96** [pyrsmk/qwest#112]
I have this method here I'm creating and I can't seem to call bind(this) on the promise chain.

```javascript
		$http_get: function ( url ) {
			this.$prog_start()
			return qwest.get( this.$httpURL + url, {
				headers: this.$http_headers()
			} ).bind( this ).then( function ( xhr, response ) { // CANT BIND THIS :(
				this.$prog_success()
				console.log( 'xhr >', xhr )
				console.log( 'response >', response )
			} ).catch( function ( err, xhr, response ) {
				this.$prog_error()
				console.log( 'err >', err )
				console.log( 'xhr >', xhr )
				console.log( 'response >', response )
			} )
		},
```
```
Uncaught TypeError: qwest.post(...).bind(...).then is not a function
```

Every other promise based library I've used I can bind(this) like that.

**Comment by pyrsmk** [comment]
PinkySwear, that is the promise dependency of qwest, does not seem to implement it at all, since it's a lightweight library.

What's the use of bind?

**Comment by roblav96** [comment]
I'm using Vue.js and almost everything needs a bind this to contain the scope. lol

I also can't use
```
.spread( function ( err, response ) {
				console.log( 'err >', err )
				console.log( 'login > response >', response )
			} )
```
Can I drop-in bluebird somehow?

**Comment by roblav96** [comment]
I really like how lightweight this library is though :D

**Comment by pyrsmk** [comment]
For `bind()`, you can't do it, but it's not a big issue since you just have to create a var : 

```js
var that = this;
// .....
that.$prog_success();
```

And what's the use of `spread()`? :p

**Comment by pyrsmk** [comment]
You cannot implement bluebird into qwest directly, I think. You should create a wrapper around it.

**Comment by roblav96** [comment]
Meh, I was trying to do compatibility fallback methods lol

**Comment by pyrsmk** [comment]
Since `bind()` and `spread()` seem specific behaviors of bluebird and are not included in the Promises spec, I'm closing this issue ;)

**Comment by roblav96** [comment]
No worries! Great library :)

**Comment by pyrsmk** [comment]
Thanks ;)
