### ISSUE TITLE
Calling abort on queued requests not working

### ISSUE THREAD

**Issue by flgarrid** [pyrsmk/qwest#115]
Hi! First of all, congrats on this amazing library.

Now my issue:
If i set qwest.limit to something different than null, all queued requests remain available after calling xhr.abort() on them.

I would expect that aborted requests on the queue must also be canceled, even if they are not triggered yet. Is it because they become somehow synchronous requests and that's not supported?

Thanks

**Comment by pyrsmk** [comment]
Thanks! You found a tricky bug :D 

Queued requests are simply stored in an array and they cannot know what is their index in that array to remove their instance from the queue. But qwest objects have an `aborted` flag that is currently not verified when the request is started. I'm fixing that and pushing a new release ;)

**Comment by pyrsmk** [comment]
I just pushed the release, please let me know if your bug is fixed

**Comment by flgarrid** [comment]
It now works if I call xhr.abort() on pending requests, but two things are happening now:

- qwest.getOpenRequests() is <0. There is a workaround if I check that xhr() != true, but doing so doesn't abort pending requests :weary: 
- The upcoming requests are not being fired immediately after I cancel previous requests. Only after I add another request to qwest, pending requests become fired.

Thanks for your quick response.

**Comment by pyrsmk** [comment]
Ok, can you test the `4.3.2`? ^^

**Comment by flgarrid** [comment]
Nope, same behavior. Let me see if I can suggest a patch and let you know, ok?

**Comment by pyrsmk** [comment]
No problem, if you found something weird inside the logic, let me know ;)

The problem should come from the `requests` variables. If `getOpenRequests() < 0` then `--requests;` is called more than expected.

**Comment by pyrsmk** [comment]
A new release is coming soon, I would be glad if you could test it against the bugs you encountered ;)

**Comment by flgarrid** [comment]
I will! Sorry I've been away for so long... have been extremely busy lately.

By coming soon you're not talking about the release 4.4.0, aren't you?

**Comment by pyrsmk** [comment]
No problem ;)

I'm talking about the `4.4.0` yes. Why?

**Comment by flgarrid** [comment]
Just asking...

I started to test your code and after patching the pinky.abort function, it worked as expected:

Based on : http://stackoverflow.com/questions/4551175/how-to-cancel-abort-jquery-ajax-request

```
pinky.abort = function() {
				if(!aborted) {
					aborted = true;
					sending = false;
					if(xhr && xhr.readyState != 4){
						xhr.abort();
						requests--;
					}
				}
			};
```

**Comment by pyrsmk** [comment]
Fixed in the last release ;) Thanks a lot for your help!

**Comment by flgarrid** [comment]
Heads up:

the code you posted has the requests-- outside of the second if statement:

```
if(!aborted) {
					if(xhr && xhr.readyState != 4) { // https://stackoverflow.com/questions/7287706/ie-9-javascript-error-c00c023f
						xhr.abort();
					}
					aborted = true;
					sending = false;
					--requests;
				}
```

and should be:

```
if(!aborted) {
                    aborted = true;
                    sending = false;
                    if(xhr && xhr.readyState != 4){
                        xhr.abort();
                        requests--;
                    }
                }
```

**Comment by pyrsmk** [comment]
Abort can be called at a bad time and `xhr.abort()` can fail. But the request is still aborted and that's why I'm using `aborted` and `sending` flags that are verified in `send()` and `handleResponse()`. So the code should be as I written it.

Do you mean that this code makes your aborts to fail?

**Comment by flgarrid** [comment]
No, no... After the last patch the code you uploaded aborts just fine. The problem is with the number of open requests being counted. In the abort function you are subtracting something that may have not be called yet, that's why requests-- must be within the  if(xhr && xhr.readyState != 4) statement.

**Comment by pyrsmk** [comment]
My problem with that is that __may__ not have been called yet. I think my method of countering requests with a simple variable is weak. I should attach a `state` value with each request then we would now exactly what request is sent, or loaded, etc... With that we could remove the problematic line from `abort()` and qwest should be more reliable too.

What do you think?

**Comment by pyrsmk** [comment]
I watched the code, and this can be easily fixed. I'm pushing a new release.

**Comment by flgarrid** [comment]
Yes! That did the trick!

Congrats, amazing work

**Comment by pyrsmk** [comment]
At last! Ahah
