### ISSUE TITLE
Cannot use qwest without CommonJs in the browser.

### ISSUE THREAD

**Issue by CVarisco** [pyrsmk/qwest#116]
Hi !
I import your library without use CommonJs Module Pattern.
```html
<script type="text/javascript" src="qwest.js"></script>
```
I get this error:
Uncaught ReferenceError: module is not defined.

Can I do somenthig ? (sorry for my english).
Thank you so much!

**Comment by pyrsmk** [comment]
I think you're not including the right file. You should use `qwest.min.js` at the root of the repository. `src/qwest.js` must be compiled in order to be used in your website.

**Comment by CVarisco** [comment]
Ops, sorry man...
With the compiled version works!

Thanks a lot.

**Comment by pyrsmk** [comment]
:+1:
