### ISSUE TITLE
Replace eval to a Function constructor in 'handleResponse' method

### ISSUE THREAD

**Issue by paulocoghi** [pyrsmk/qwest#118]
I am not a very experienced javascript developer, but I would like to know the opinion of contributors.

I am trying to use Qwest as a library in combination with a new framework I am building, bundling it with [Roolup](http://rollupjs.org/). I really like the way qwest works.

But, since we have an `eval` in qwest (line 17047), I am finding barriers to continue with it (when trying to bundle it as a module to my library).
```javascript
response = eval( '(' + xhr.responseText + ')' );
```

Following [a tip from Rollup devs about this issue](https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval), using the [Function constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) would be a little safer and also much faster.

I would like to suggest the change bellow, with your opinions:

```javascript
response = new Function( 'return (' + xhr.responseText + ')' )();
```

Also, I want to congratulate the work you have already done!

**Comment by pyrsmk** [comment]
Hi! Thanks for the consideration you're giving to qwest ;)

I didn't know Rollup! Is it a standalone library? Is it compiling ES6 by itself or we need to use Babel?

Anyway, as `new Function()` seems to be supported everywhere, I see no problem to replace `eval()`. I'm pushing this issue with the others for the next version. I think I'll release it in a couple of days, max.

PS : since you're creating your framework, you may be interested in [quark](https://github.com/pyrsmk/quark)

**Comment by paulocoghi** [comment]
Rollup is the module bundler I was waiting for (and [JSPM](http://jspm.io/) follow the same path, using Rollup in its bundler).

It establishes the [ES2015/ES6 modules](http://jsmodules.io/) as the default standard, and works [in a brilliant way](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80). The "tree-shaking" feature is incredible and, yes, you can optionally [use it with Babel](http://rollupjs.org/guide/#using-rollup-with-babel) ([plugin](https://github.com/rollup/rollup-plugin-babel)).

You can use modules from other sources, like [npm](https://github.com/rollup/rollup-plugin-node-resolve), and [convert them to ES6 modules](https://github.com/rollup/rollup-plugin-commonjs) to be able to bundle them through Rollup.

That's it :)

Sorry for my excitement (and my intermediary English). I really like the work that Rich Harris has been doing for the javascript community.

**Comment by pyrsmk** [comment]
This module bundler is really interesting! I think I'll use it ASAP with all my libs/frameworks! I can understand your excitement, I was waiting for a thing like Rollup for some time. I currently use browserify with gulp, but I don't like it. It's complicated to get what you want from your final bundle...

PS : my english is poorer than yours :p

**Comment by pyrsmk** [comment]
Fixed in the next release
