### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [pyrsmk/qwest#119]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

Could you add a **dist** or **build** folder and put ```qwest.min.js``` and ```qwest.js``` together?
Then I can config the git auto-update more easier.

Thanks!
https://github.com/cdnjs/cdnjs/pull/7813

**Comment by x09326** [comment]
Sorry, I can just modified the config.

**Comment by pyrsmk** [comment]
Perfect ;)
