### ISSUE TITLE
Undefined XMLHttpRequest

### ISSUE THREAD

**Issue by grafa** [pyrsmk/qwest#122]
Hey mate,

I've upgraded from 4.4.1 to 4.4.3 and I'm getting error when I run my code in browser (not while compiling by webpack).

The error is about calling property XMLHttpRequest of undefined in file and line https://github.com/pyrsmk/qwest/blob/master/src/qwest.js#L19

When I rollback to 4.4.1 everythings works fine.

**Comment by pyrsmk** [comment]
My tests are running well. In your case `global` seems to be undefined, which is set to `this`. If the library is not wrapped, `this` should be `window`. So, if `global` is undefined, it should be because `window` is not reached. How do you run qwest in your browser?

**Comment by grafa** [comment]
It's used inside my class and packed with webpack. As I said 4.4.1 is OK, there must be some particular change that causes this.

**Comment by pyrsmk** [comment]
Yep, the change : https://github.com/pyrsmk/qwest/commit/6259f5d521d03973f2555ce7367658f025136586
Because of : https://github.com/pyrsmk/qwest/issues/78#issuecomment-214465087

I think I should changed this line by : `var global = typeof window != 'undefined' ? window : self`

**Comment by pyrsmk** [comment]
Tell me if it's working now ;)

**Comment by pyrsmk** [comment]
Then? ^^
