### ISSUE TITLE
Is it possible to cancel a request

### ISSUE THREAD

**Issue by phillip-haydon** [pyrsmk/qwest#124]
If a request has started but not yet completed, can it be canceled?

i.e

```javascript
var request = qwest.get(...)
                   .then(...);

request.cancel();
```

When get is completed, then `then` will not be called because it was canceled.

**Comment by pyrsmk** [comment]
It's in the [docs](https://github.com/pyrsmk/qwest#aborting-a-request)

**Comment by phillip-haydon** [comment]
Hah, I spend ages looking at the docs for 'cancel' and it never occurred to me that it would be called abort. 

Thanks!

**Comment by pyrsmk** [comment]
Ahah, np ;)
