### ISSUE TITLE
Does not run in Node.js

### ISSUE THREAD

**Issue by firstdoit** [pyrsmk/qwest#125]
Because of this [evaluation of self](https://github.com/pyrsmk/qwest/blob/master/src/qwest.js#L5), `qwest` explodes in the node environment.

```
/Users/guilherme/Projects/VTEX/render/node_modules/qwest/src/qwest.js:5
    var global = typeof window != 'undefined' ? window : self,
                                                         ^

ReferenceError: self is not defined
    at /Users/guilherme/Projects/VTEX/render/node_modules/qwest/src/qwest.js:5:55
```

Do you want me to add a condition to use `global` or is Node not intended to be supported by `qwest`?

**Comment by pyrsmk** [comment]
Qwest is based on XHR, which is only available on browsers, isn't it? Then, Node will never be supported ^^

**Comment by firstdoit** [comment]
Derp! Didn't notice that. 😁 

Thanks!

**Comment by pyrsmk** [comment]
Ahah np ^^

**Comment by tm57** [comment]
I fell for this recently, even if qwest is for browsers, usually some of us build our assets using node, and qwest fails. For example, when optimising js using the requirejs optimizer, same error occurs. I feel this needs attention, no?

**Comment by pyrsmk** [comment]
It sure does. What are the errors you encountered?

**Comment by tm57** [comment]
<img width="936" alt="screen shot 2017-03-13 at 20 15 18" src="https://cloud.githubusercontent.com/assets/7309040/23871287/052b6932-082a-11e7-8878-6296e4b63762.png">

**Comment by pyrsmk** [comment]
Ok, I will fix this issue with the upcoming v5 version (a complete rewrite).

**Comment by pyrsmk** [comment]
Mmmmh... I was thinking... If you're building your assets under node, and you encounter a bug with an undefined variable because the variable is not defined in the current environment, shouldn't you define vars to ignore (like with jshint) instead of relying on qwest to support this environment?

**Comment by pyrsmk** [comment]
For now, I'm closing this issue until new thoughts on this ;)
