### ISSUE TITLE
Referencing responseText when responseType is 'json'

### ISSUE THREAD

**Issue by robyoder** [pyrsmk/qwest#127]
In certain situations, I'll get an error from a request in Chrome that looks like this: `DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').`

It links me directly to this code in qwest:

```
case 'json':
	if(xhr.responseText.length) {
		try {
			if('JSON' in global) {
				response = JSON.parse(xhr.responseText);
			}
			else {
				response = new Function('return (' + xhr.responseText + ')')();
			}
		}
		catch(e) {
			throw "Error while parsing JSON body : "+e;
		}
	}
	break;
```

Seems like the referencing of `xhr.responseText` is pretty intentional, but it's causing problems. Thoughts?

**Comment by pyrsmk** [comment]
This code is a fallback when the `json` response type is not supported by the browser. What kind of situations gives you this error?

**Comment by robyoder** [comment]
In this case, it was a server error that returned a response with these headers:

```
HTTP/1.1 200 OK
Cache-Control: max-age=60, no-cache, no-store
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Date: Sat, 30 Jul 2016 19:05:28 GMT
Content-Length: 23
Content-Type: application/x-gzip
```

Despite the `Content-Length: 23`, Chrome said "This request has no response data available", and the `response` attribute of the XMLHttpRequest, was `undefined`, not `null`. So it would not have passed this check in the qwest code:

```
if(nativeResponseParsing && 'response' in xhr && xhr.response !== null) {
	response = xhr.response;
}
```

**Comment by robyoder** [comment]
So it looks like it doesn't have anything to do with `json` response type not being supported by the browser (the `nativeResponseParsing` part), but simply the fact that the response was empty.

**Comment by robyoder** [comment]
In Firefox, the error for the same offense is `InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`

**Comment by pyrsmk** [comment]
So can the problem come from the server or the data you're returning, eventually?

**Comment by robyoder** [comment]
I'm not sure I understand your question. The server should be returning a better response here, yes, but qwest should not be trying to read `responseText` when the `responseType` is json, especially if `response` is null.

**Comment by pyrsmk** [comment]
I agree. It does not handle failed requests after a certain point and it's assuming the response is available. I'm pushing a new release in a couple of hours.

**Comment by pyrsmk** [comment]
It's out ;) Tell me if the problem persists.

**Comment by robyoder** [comment]
Looks good, thanks!
