### ISSUE TITLE
qwest post data is received by the server as strings only

### ISSUE THREAD

**Issue by tzookb** [pyrsmk/qwest#129]
I really dont know where is the issue and why.

I use a simple qwest post request

```
 qwest.post('/post/opinion', {bool: true, int: 1})
        .then(function(xhr, response) {
            resolve(response);
        })
```

in the php laravel server I get the data but both attributes are strings instead of boolean and integer.

Any ideas?

thanks!

**Comment by pyrsmk** [comment]
The `dataType` option is set to `post` by default. To send json data, you must set `dataType` to `json`.

I think I should change the default value by `json` instead of `post` for XHR2 requests. I don't why I set the default value to this at first :p

**Comment by pyrsmk** [comment]
FYI, `post` are sending data as string, as the HTTP protocol supports it. The only way to get typed data is to send it in JSON and parsing it in the server side.
