### ISSUE TITLE
Add an additional parameter in order to be able to pass default timeout handler.

### ISSUE THREAD

**Issue by dcantir** [pyrsmk/qwest#130]
I need to do some actions when a timeout occurs, but seems this isn't possible now.

**Comment by pyrsmk** [comment]
I want to plan this for the future release. Is this blocking what you want to achieve?

**Comment by dcantir** [comment]
I think yes, because I am not able to find an elegant solution right now

**Comment by pyrsmk** [comment]
I think the simplest way for now is to add a `catch` callback and then match the error parameter against `timeout` string.

```js
qwest.get()
     .then()
     .catch(function(e, xhr, response) {
        if(e.message.indexOf('timeout') != -1) {
          // timeout
        }
     });
```

**Comment by pyrsmk** [comment]
So, did it work?

**Comment by dcantir** [comment]
The code above works, but it's not what I was looking for. Instead I reduced timeout fastcgi param and now I am handling the timeout in `catch` block.

**Comment by pyrsmk** [comment]
Then I don't exactly understand what was your needs ^^ But since it's working for you, I'll close this.
