### ISSUE TITLE
Why my headers are concatenated with "HTTP_"?

### ISSUE THREAD

**Issue by jnavarro1512** [pyrsmk/qwest#134]
![image](https://cloud.githubusercontent.com/assets/18235244/22003327/c2feb5c6-dc20-11e6-96b8-542bb5452b4a.png)

![temp](https://cloud.githubusercontent.com/assets/18235244/22003401/47829be6-dc21-11e6-8382-d14d60bc066e.png)

**Comment by pyrsmk** [comment]
I think that XHR2 prepends `HTTP_` to your headers. Or it's the Apache server. But not qwest ^^ And, for me, it's not a bug but a normal behavior since your headers are not "officials".
