### ISSUE TITLE
How to use it together with Promise.all()?

### ISSUE THREAD

**Issue by mikk150** [pyrsmk/qwest#140]
I am trying to do smth like this
```
        var promises = global.config.servers.map(function (server) {
            return qwest.post(server.host + '/api/whatever');
        });
        return Promise.all(promises).then(function (xhrs, responses) {
            console.log(responses);
        });
```

But I only get xhrs array

**Comment by pyrsmk** [comment]
Mmmh. In fact, the way qwest's using promises is non-standard, as the Promise based library that's being used is obsolete too. A complete rewrite is planned but I don't have much time. Anyway... Normally, a fulfilled promise does return only one value (in qwest, we're returning `xhr` and `response`). Then `Promise.all()` is only getting the first parameter to create its response array.

So, if you want to achieve what you need, you must do something like : 

```js
var promises = global.config.servers.map(function (server) {
    return qwest.post(server.host + '/api/whatever').then(function(xhr, response) {
        return response;
    });
});
```

**Comment by mikk150** [comment]
I ended up using this
```js
var promises = global.config.servers.map(function (server) {
    return new Promise(function (resolve, reject) {
        qwest.post(server.host + '/api/whatever').then(function (xhr, response) {
            resolve(response)
        }, reject)
    }) 
});
```

**Comment by pyrsmk** [comment]
:+1:
