### ISSUE TITLE
qwest is unexpectedly adding parameters to the URL

### ISSUE THREAD

**Issue by berstend** [pyrsmk/qwest#145]
Hi there,
thanks for qwest!

I ran into an issue and wanted to check if this expected/wanted behavior:

```es6
import * as qwest from "qwest";
qwest.limit(10);

async function doRequest(url) {
  const req = await qwest.get(url, {
    responseType: "text",
    timeout: 5000,
    attempts: 5
  });
  return req.response;
}

doRequest("https://www.httpbin.org/anything").then(e => console.log(e));
```

This will result in a request to the following url: https://www.httpbin.org/anything?responseType=text&timeout=5000&attempts=5

Is adding these internal query strings to the URL intended or required for the business logic to work?
I just ran across this issue as my code further down didn't expect those parameters.

Is there a config to disable mutating the URL? :-)

Thanks!

**Comment by berstend** [comment]
I found one hacky workaround which I'm using for now, but it's definitely not optimal:

```es6
import * as qwest from "qwest";
qwest.limit(10);

qwest.setDefaultOptions({
    timeout: 5000,
    attempts: 5,
    responseType: "text",
});

async function doRequest(url) {
  const req = await qwest.get(url);
  return req.response;
}
doRequest("https://www.httpbin.org/delay/10")
  .then(e => console.log(e))
  .catch(err => console.warn(err))
```

When shoving everything in `qwest.setDefaultOptions` the options are being used but the URL stays unaltered. 😄

**Comment by paulocoghi** [comment]
In your first example, you were passing options as a second parameter. Thus, your options were treated as data. In `get` methods, data is passed as url variables.

To do what you want, without relying in `setDefaultOptions`, you need to pass your options as the third parameter:

```javascript
import * as qwest from "qwest";
qwest.limit(10);

async function doRequest(url) {
  const req = await qwest.get(url, , {
    responseType: "text",
    timeout: 5000,
    attempts: 5
  });
  return req.response;
}

doRequest("https://www.httpbin.org/anything").then(e => console.log(e));
```

The little difference is the comma. From:

```javascript
const req = await qwest.get(url, {
```

To:

```javascript
const req = await qwest.get(url, , {
```

---

In Qwest documentation, you can see better the order of parameters:

```javascript
qwest.`method`(`url`, `data`, `options`, `before`)
     .then(function(xhr, response) {
        // Run when the request is successful
     })
     .catch(function(e, xhr, response) {
        // Process the error
     })
     .complete(function() {
         // Always run
     });
```

**Comment by pyrsmk** [comment]
@paulocoghi explained it well! Indeed, the second parameter is for `data` and not `options`. Moreover, with a `GET` method, `data` is passed into the URL. If I'm right, that's a convention from the HTTP protocol. The XHR doesn't handle data passed as POST data for GET requests, thus qwest pass it into the URL instead.

**Comment by berstend** [comment]
Oh wow, how could I overlook that! 😅 Thanks a lot @paulocoghi and @pyrsmk

**Comment by paulocoghi** [comment]
> If I'm right, that's a convention from the HTTP protocol.
Yes, you are right :blush:

**Comment by pyrsmk** [comment]
Glad to help!
