### ISSUE TITLE
Promises don't seem to work properly

### ISSUE THREAD

**Issue by josephfinlayson** [pyrsmk/qwest#22]
```
var request = $http.get('https://www.googleapis.com/youtube/v3/search', {
    key: apiKey,
    type: 'video',
    maxResults: '1',
    part: 'id,snippet',
    fields: 'items/id,items/snippet/title,items/snippet/description,items/snippet/thumbnails/default,items/snippet/channelTitle',
    q: searchTerm || 'neil young alabama'
}, {
    responseType: 'json'
}).then(function() {
    console.log("request!");
    return {
        a: 'b'
    }
}).then(function(data){
    console.log(data)
})
```

data is the request object, when it should be `{a:b}`

**Comment by pyrsmk** [comment]
I'm implementing a better promises spec and this behavior will be dropped in the next release because it's not standard at all.

**Comment by pyrsmk** [comment]
The future passed vars with `then` callbacks are `xhr, response`. There will be no way to pass any other variable, and if you want to it seems you should re-think your architecture ;)

**Comment by pyrsmk** [comment]
Don't care about my previous messages, I was completely wrong. The promises spec still seems really weird to me.

**Comment by josephfinlayson** [comment]
Just put a dependency on bluebird, or a lightweight promise implementation

**Comment by pyrsmk** [comment]
That's what I did. Qwest 2 is now out ;)
