### ISSUE TITLE
XDomainRequest fails with an error if responseType is "auto" since XDomainRequest doesn't support getResponseHeader

### ISSUE THREAD

**Issue by agusgriego** [pyrsmk/qwest#24]

**Comment by pyrsmk** [comment]
As the error points out, XDomainRequest does not support the `getResponseHeader()` method, which is used in `auto` mode to guess what is the type of the returned response according to its `Content-Type` header.

Long story short : you need to define explicitly the reponse type.

But thanks for the report! I'll write a note about it in the documentation and block the use of the `auto` mode with XDR.

**Comment by agusgriego** [comment]
Instead of throwing an error, you could use the default (text) in XDR requests unless the response type is specified... I made a quick fix and I'm using it that way. It's better than make the request fail or make the user specify each response type...

**Comment by pyrsmk** [comment]
You're right ^^ Should be better that way

**Comment by pyrsmk** [comment]
Isn't it better to set it to `json` by default instead of `text`?

**Comment by pyrsmk** [comment]
Because, json is more used than a classic, typeless, text response type.

**Comment by agusgriego** [comment]
I guess it depends on how you use it... For example, I'm using it to load external Javascript and CSS files. I suggested "text" because that is the "default" in the switch statement :)

**Comment by agusgriego** [comment]
Or you could leave it at JSON and let the user override that default if he wants (like you do with limit)

**Comment by pyrsmk** [comment]
That should do the trick, I think

**Comment by agusgriego** [comment]
Yep, that's a good one. Thanks!!

**Comment by pyrsmk** [comment]
The last commit should have fixed the issue. Reopen it if you encounter some problems (because I do not have write tests for this, as it's a very trivial modification). Thanks for your help ;)
