### ISSUE TITLE
Strange issue with Firefox 35

### ISSUE THREAD

**Issue by agusgriego** [pyrsmk/qwest#29]
I deployed the library to production (~ 20k daily active users) and been getting a very strange error sometimes in Firefox 35. I could never reproduce it myself but the log showed ": " as the error message (semicolon plus space).
The error happened in the line where this occurs: xhr.open(method,url,options.async,options.user,options.password);
I fixed it by adding a try catch statement with a few retries when issuing that command. Though I'd let you know.

**Comment by pyrsmk** [comment]
Very strange, indeed... Do you think previous Firefox versions are concerned too?
Maybe they've changed something in the supported API, but it seems that it's a Firefox bug...

**Comment by pyrsmk** [comment]
Do you use some options on your qwest calls?

**Comment by pyrsmk** [comment]
So... Somebody reopen if needed.
