### ISSUE TITLE
write test harness in node, not php

### ISSUE THREAD

**Issue by danielr-minted** [pyrsmk/qwest#31]
You already have node as a requirement.  Writing the server side of the tests in javascript and node would make the test harness much easier to run.  I still haven't figured out how to get php working on mac os x.  A node based backend could be as easy as node tests/server.

**Comment by pyrsmk** [comment]
You're right. I just don't have much time for this, and I'm not really used to nodejs at the time. If you have the time to migrate the tests, I'd be pleased :p

**Comment by pyrsmk** [comment]
I'm closing it by lack of time to migrate PHP tests. If someone want to contribute, please reopen ;)
