### ISSUE TITLE
Accept header set to null for many data types

### ISSUE THREAD

**Issue by danielr-minted** [pyrsmk/qwest#34]
Accept header is set to the value of "null" for mimeTypes for arraybuffers, formdata, document, file or blob.

**Comment by pyrsmk** [comment]
Hum. Is this an affirmation or...?

**Comment by danielr-minted** [comment]
It's a bug.  Accept header should never be a value of null.  One sec...

**Comment by pyrsmk** [comment]
I see... That should do the trick, thanks ;)

**Comment by danielr-minted** [comment]
Also, FormData has a mimetype of "multipart/form-data", it's just that XHR2 sets it correctly when you don't explicitly set content-type.  Though you're probably not expecting multipart/form-data back when you send a FormData object.  Basically in general it is not always the case that the response content-type matches the request content-type.

Also in all cases you'd probably be better off using the full syntax and making sure that the server can fall back to any type...  e.g.
```
Accept: text/json; q=1.0, text/*; q=0.8, */*; q=0.1
```
e.g. accept text/json, then any text format, then */* if all else fails.  It is much safer to let the server always be able to fall back to */* with a lower q setting.

**Comment by pyrsmk** [comment]
Indeed. As mentioned in the docs, only a few value is used for the `Accept` header :

```
responseType : the response type; either auto (default), json, xml, text, arraybuffer, blob or document
```

I don't know which mime type to pick for `arraybuffer`, `blob` or `document`. Because it's us that set the response type, we should force the `Accept` header as requested and the server should return the requested response as expected, isn't it?

**Comment by danielr-minted** [comment]
The problem is that if the server can't produce the content specified in the accept header, it is required to return 406.  Lots of servers in the wild may be configured with an unexpected content type.  If you accept */* as a fallback, you protect yourself against a surprise 406.  '*/*' is fine for arraybuffer or blob, but anytime you still want forms like 'Accept: text/json; q=1.0, */*; q=0.1' so that your lib will work with bad servers.

**Comment by pyrsmk** [comment]
I see... Thanks for your help, I'll try to update mime types accordingly.

**Comment by pyrsmk** [comment]
I'm currently implementing the use of the following `Accept` headers. What do you think?

```js
accept={
	text: 'text/plain; q=1.0, text/*; q=0.8, */*; q=0.1',
	xml: 'application/xml; q=1.0, text/xml; q=0.8, */*; q=0.1',
	json: 'application/json; q=1.0, text/*; q=0.8, */*; q=0.1'
}
```

**Comment by pyrsmk** [comment]
Additionally, XHR now can set the mime type by itself as a fallback.
