### ISSUE TITLE
Gruntfile.js breaks when you have vim open

### ISSUE THREAD

**Issue by danielr-minted** [pyrsmk/qwest#36]
If you have an editor that creates addition files in the src directory (like .*.swp from vim or emacs ~ files), then your grunt file picks up those files as libraries and chokes on them.  In particular, when I have vim editing quest.js, I get this cryptic message from grunt:

```
Daniel-Rs-MacBook-Pro:qwest danielr$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property '1' of null
```

**Comment by pyrsmk** [comment]
That's the watch task that crashes. I don't think I can do anything, there's not much stable plugins for simply watching files. Maybe, can you do a `npm update`?

Otherwise, I can migrate grunt to gulp in the future.

**Comment by pyrsmk** [comment]
Ah. I misunderstood, once again, the problem ^^;
I should update the build system on all my libraries, they share more or less the same Gruntfile.
