### ISSUE TITLE
Promises should resolve returning thenable

### ISSUE THREAD

**Issue by danielr-minted** [pyrsmk/qwest#37]
the following should work, according to https://promisesaplus.com/ and the promise specification

```javascript
aPromise  = Promise.resolve('a')

aPromise.then(function (a) {
  //returning a thenable from then should chain the thenable properly
  return Promise.resolve('b').then(function (b) {
    return a+b
  });
})
.then(console.log.bind(console));
```
See https://promisesaplus.com/#point-49

Also that code works as is in firefox, chrome or safari.  A workaround is to wrap qwest promises with new Promise();

**Comment by danielr-minted** [comment]
I misspoke.  The best workaround I have is to include a solid Promises library (like when), that can turn an arbitrary thenable into a conformant promise.

Btw, most of the difficult here can be resolved by just doing new Promise() and optionally including a polyfill for promises, instead of implementing it yourself.

**Comment by pyrsmk** [comment]
I don't understand that issue. Isn't it already the case that promises are chainable in qwest?
Also, this implementation seems strongly related to #27

**Comment by danielr-minted** [comment]
Returning a promise from the resolve function doesn't chain properly.  The example code above doesn't work with your promise implementation.

**Comment by pyrsmk** [comment]
Since this issue is part of #51, I close it.
