### ISSUE TITLE
option: retries = 0 falls back to 3 retries

### ISSUE THREAD

**Issue by muellerkyle** [pyrsmk/qwest#40]
The following line causes an issue where, if you has set the retries option to `0`, `0` gets coerced into a falsey value, and therefore falls back to 3 retries. Note, the issue lies on line 288 of the version of code that I have.

Path: `/src/qwest` Line 288

Code:
```js
options.retries=options.retries?parseInt(options.retries,10):3;
```

Could you consider alternative logic, instead? Such as:

```js
options.retries=( typeof options.retries === "undefined" || Number.isNaN(options.retries) ) ? 3 : parseInt(options.retries,10);
```

**Comment by pyrsmk** [comment]
A simple `options.retries = 'retries' in options ? parseInt(options.retries,10) : 3;` should do the trick ;)

**Comment by pyrsmk** [comment]
Should be fixed by now, please reopen if you sill have a problem.

**Comment by muellerkyle** [comment]
Thanks!
