### ISSUE TITLE
1.5.8 fails with browserify

### ISSUE THREAD

**Issue by evilfer** [pyrsmk/qwest#41]
browserify fails with qwest 1.5.8 (1.5.7 working). Could it be related to the fact that qwest package index property is set to "src/qwest.js", yet this file is not distributed with this version? (only qwest.min.js is present).

**Comment by pyrsmk** [comment]
How does it fail? What is your error?
On my side, I have no error with installing qwest 1.5.8.

**Comment by evilfer** [comment]
Error report below. qwest is not installed globally by the way. I also checked that 1.5.7 did include the src folder.

Error: Cannot find module 'qwest' from '<project root>\src\js'
    at <project root>\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (<project root>\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (<project root>\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (<project root>\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (<project root>\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at <project root>\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)

**Comment by codejet** [comment]
I get the same error

**Comment by pyrsmk** [comment]
It seems there's a conflict the `package.json`. I'll push a new version in the following minutes.

**Comment by pyrsmk** [comment]
Please update and tell me if it's working again

**Comment by evilfer** [comment]
Browserify task working now, thank you!

**Comment by pyrsmk** [comment]
Good to hear, and sorry for the inconvenience ;)
