### ISSUE TITLE
Issue in latest release with package.json

### ISSUE THREAD

**Issue by dev-tim** [pyrsmk/qwest#42]
There is misconfigured package.json which points to ```"main": "src/qwest.js",```
However in .npmignore there is excluded src folder:

```
.git/
.gitignore
nodes_modules/
src/
tests/
Gruntfile.js
package.json
```

**Comment by pyrsmk** [comment]
Duplicate of #41

**Comment by pyrsmk** [comment]
Sort of :p

**Comment by pyrsmk** [comment]
Please update and tell me if it's working again

**Comment by dev-tim** [comment]
Thanks ;)

**Comment by pyrsmk** [comment]
Np ;) Thanks for posting the issue.
