### ISSUE TITLE
Accepted/correct format for options.headers

### ISSUE THREAD

**Issue by paulocoghi** [pyrsmk/qwest#45]
What is the correct format for the `header` object (that is passed to the `options` parameter).

Is this example an accepted format?

```javascript
{
    Authorization : 'Bearer a71jd74ka73jh... ',
    Another-Example-Header : 'The content for this another header',
}
```

In other words, do I need to put the header name as the property name and the header content as the property content?

(sorry if this question is too basic)

**Comment by pyrsmk** [comment]
This is exactly how you should handle headers ;)
I should add an example to the doc.

**Comment by paulocoghi** [comment]
Feeling happy to contribute :)
