### ISSUE TITLE
null parameter is not permitted

### ISSUE THREAD

**Issue by mrmartineau** [pyrsmk/qwest#46]
I am trying to get a simple GET request to work with Qwest. It should be easy but its not because I get this error in my devtools:

`null parameter no permitted`

It seems qwest is adding a `null` param to the request that the API doesn't like. Your docs say to set the data part to `null` if not needed, when I do that it adds null as a param in the request. Is that expected behaviour?

Here is a shortened version of my code:

```js
var qwest = require('qwest');
qwest.get('http://live.storystream.it/api/v2/ACCOUNT_ID/search/published/?types=social&rpp=4&access_token=ACCESSTOKEN', null, {
		dataType : 'json',
		cache : true
	})
	.then(function(response){
		console.debug(response);
});
```

I have a feeeling that the API I'm using is being quite strict but if there's a way to remove the null value, I would love to know what it is.

Cheers

**Comment by pyrsmk** [comment]
In fact, having a `null` parameter for data shouldn't throw an error. If you set data with `{}` what's happening?

Furthermore, what's the browser/os where you get the error?

**Comment by mrmartineau** [comment]
I tried with `{}` and that didn't work either. Unfortunately I have had to choose another lib due to time constraints. 

Also, if I set `cache: false` then it adds a timestamp (`__t`) parameter which also throws an error.

**Comment by pyrsmk** [comment]
Hum ok. Can you give me the browser where you have the error, and your operating system. Moreover, I need to have the line where the error has been encountered (in the console). That way I could understand what's going wrong ;)

**Comment by mrmartineau** [comment]
Sure, I will try later but I'm up against it on this project so it may not be today. Thanks for your help so far. Also, I am using reqwest now but I'd rather use yours as its a much smaller library...

**Comment by pyrsmk** [comment]
Thanks in advance ;) And sorry for the inconvenience.

**Comment by pyrsmk** [comment]
By looking your code a bit closer, I think that the problem comes from your `dataType` option. This options specifies that your data you want to send should be encoded in `json`. But your data is `null`. I think you otherwise wanted to set `responseType` to `json` and not `dataType`. Moreover, a `json` `responseType` has no need to be specified since qwest can detect it automatically.

**Comment by mrmartineau** [comment]
I'm going to try it again now and will let you know the results.

**Comment by mrmartineau** [comment]
You are completely right, I managed to test it again last night. I needed this:

```js
qwest.get(apiEndpoint, null, {
		cache : true,
		responseType : 'json'
	})
```
I was certain that I'd tried that option but obviously I hadn't, thanks for your help

**Comment by pyrsmk** [comment]
Good to hear :)
