### ISSUE TITLE
Throws error if content-type is missing in header

### ISSUE THREAD

**Issue by mdix** [pyrsmk/qwest#50]
If there's no Content-Type set in the header, qwest breaks with the following error:

`"Cannot read property 'indexOf' of null"`

The error is caused because the else branch of the following code assumes that there's 'Content Type' in the header:

```
if(responseType=='auto'){
    if(xdr){
        responseType=defaultXdrResponseType;
    }
    else{
        var ct=xhr.getResponseHeader(contentType);
        if(ct.indexOf(mimeTypes.json)>-1){
            responseType='json';
        }
        else if(ct.indexOf(mimeTypes.xml)>-1){
            responseType='xml';
        }
        else{
            responseType='text';
        }
    }
}
```

There should be an additional check that falls back to text if nothing is set:

```
if (ct.length < 1) {
    responseType='text';
}
```

Best
Marc

**Comment by pyrsmk** [comment]
In which environment/context a `Content-Type` header is not sent by the server?

**Comment by mdix** [comment]
Hi,

well it's just an nginx testserver we're running and it's not sending the content-type. Beneath the fact that it might be a wrong configuration, qwest shouldn't assume the existence of content-type but check for it and either output a proper error or assume someting.

Best
Marc

**Comment by pyrsmk** [comment]
Totally agree with you. I'm on that ;)

**Comment by pyrsmk** [comment]
Can you try to change the line `var ct=xhr.getResponseHeader(contentType);` by `var ct=xhr.getResponseHeader(contentType) || '';` and tell me if it's working?

**Comment by mdix** [comment]
I cannot reproduce the bug without committing a broken version and I don't really want to do that. 

As far as I can judge your fix should work. In my case `xhr.getResponseHeader(contentType)` returned `null`, which now would cast to `false` and therefor the `''` after the or is assigned, what results in `ct` being a string. Therefor `indexOf()` will exist, but will return -1 on every ocassion and finally the responseType will be set to `'text'`.

Thanks for fixing it!

**Comment by pyrsmk** [comment]
Thanks for reporting it ;) Should be fixed with latest commit
