### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by pyrsmk** [pyrsmk/qwest#51]
`2.0` should be a complete rewrite in ES6 for a cleaner code.

**Comment by pyrsmk** [comment]
Since there's a BIG lack of understandable documentation/articles for ES6 and too many ways to support it, I chose to remove the writing of qwest with ES6. We'll see that later.

**Comment by pyrsmk** [comment]
Don't hesitate to cleanup things like variables or anything else.
After qwest is ported, I'll run tests against it, and verify the overall code.

Otherwise, I'll migrate some code to another libraries as seen in #57, #59 and some other issues. So, I think you should adapt the library to remove unused code and add some requires if you have time.

Anyway, I've created the ES6 branch ;)

**Comment by singerxt** [comment]
@pyrsmk We would need change names for some of qwest methods.

For example get => $httpGet because get is reserved word in ES6

**Comment by pyrsmk** [comment]
That would be really ugly :(
If we need to change some method names, we'll need to change all methods according to a specific scheme.
Maybe we should have a look to the `window.fetch` proposal to find something new?

**Comment by singerxt** [comment]
Could you explain ? put some examples ;-)

**Comment by pyrsmk** [comment]
Yeah, I forgot that :p 

https://github.com/github/fetch

**Comment by singerxt** [comment]
So instead of 'get' method you want to rename it to fetch ? ;-)

**Comment by pyrsmk** [comment]
It's an example yeah. You can have one global method for requiring data, and put a `method` option. With that option defaulting to `get`.

**Comment by singerxt** [comment]
Sure thing. ;-)

**Comment by pyrsmk** [comment]
Cool:)

Thanks a lot for taking time for this major rewrite!

**Comment by pyrsmk** [comment]
For the method name, what are your thoughts? Because `fetch` would be ambiguous with `fetch` spec.  `request` can be a long name too.

Or maybe we can just use the constructor for global function (beeerk design beeerk). That way we can do a simple `qwest(url).then();`.

**Comment by singerxt** [comment]
I'm testing some stuff now and looks like compiler do not send any error when I write method get().

```

class test () {
  get () {
    // magic from qwest
  }

  // define getter 

  get test () {
      return 'test'
  }
}

let tests = new test();

tests.get() //qwest magic.
test.test; // 'test'
```

So maybe we can use old methods name. They are making sense. I'll let you know later.

**Comment by pyrsmk** [comment]
I agree ;)

**Comment by singerxt** [comment]
I will keep old method names so we can try keep version 2.0 compatible with 1.7.0

**Comment by pyrsmk** [comment]
Without rewrite tests, good idea ;)

**Comment by singerxt** [comment]
Hello @pyrsmk you can review current work and let me know if you have any ideas. I understand qwest is still your baby - Actually I'll follow Airbnb code standards https://github.com/airbnb/javascript let me know if you have issues with that.

**Comment by pyrsmk** [comment]
No problem with code standards, do as you need ;)

For your work I'll take a look monday if possible.

**Comment by pyrsmk** [comment]
I've planned to suspend ES6 conversion for now, I'll probably reopen this later.
