### ISSUE TITLE
Automatic retries and 3s timeouts are wrong defaults

### ISSUE THREAD

**Issue by sirwart** [pyrsmk/qwest#53]
It's not safe to assume a server call is idempotent, meaning you can automatically retry without issues. A call that post a comment that is taking longer than 3s to process will by default get called 3 times in a row, which can potentially post 3 comments. Most services that deal with HTTP have a 30s-60s timeout, which seems like a more reasonable default (and can be dropped lower for a call if appropriate)

**Comment by pyrsmk** [comment]
You're right. We should assume that a request should complete as well in a normal context. I'll fix that in the next release.
