### ISSUE TITLE
Crashing on empty response text

### ISSUE THREAD

**Issue by makrolabs** [pyrsmk/qwest#54]
When the response is valid 200 but has no text, then qwest crashes with the following error. This should not happen.

Error: Cannot read property 'indexOf' of null

TypeError: Cannot read property 'indexOf' of null
    at XMLHttpRequest.handleResponse (http://localhost:3099/app/bower_components/qwest/qwest.min.js:2:2654)

**Comment by pyrsmk** [comment]
Thanks for reporting it, I'll investigate this ASAP.

**Comment by pyrsmk** [comment]
Which version of qwest are you using?

**Comment by pyrsmk** [comment]
(oops)

**Comment by pyrsmk** [comment]
Because it seems you have encountered an old bug that is fixed by now. Please update qwest if you have not the latest version. If the issue persists, can you test with the source version of qwest (non minified), and copy/paste me the error?

**Comment by makrolabs** [comment]
you are right, i got this error with the current version from the bower repository which is 1.5.11

when using 1.5.12 from the github repository this problem does not occur

**Comment by pyrsmk** [comment]
The bower repository is not up-to-date? Good to know!
