### ISSUE TITLE
Relying on different status codes

### ISSUE THREAD

**Issue by message** [pyrsmk/qwest#61]
Aurélien, i love your library, it's clean and sophisticated. I heavily rely on different http status codes, and with e.g. HTTP 400 Bad Request i send JSON data back. Would you consider to add to `catch` method third param `data`?

To run everytime `JSON.parse` is annoying, and that change doesn't worth forking... Your thoughts?

**Comment by pyrsmk** [comment]
Hi message! Thanks for your interest for qwest ;)

For your request, I'm not really sure on how to handle this properly (not in the code, but in the concept). Should the server return a body even with a 400 status code?

**Comment by message** [comment]
Yep, why not? [JSON API](http://jsonapi.org/format/#crud) says that 409 **SHOULD** include error details and provide enough information to recognize the source of the conflict.

**Comment by pyrsmk** [comment]
No problem, I'm considering how to implement this ;)

**Comment by pyrsmk** [comment]
Otherwise, I'm thinking about the second param `url`. I'm not really sure if it's really useful.

**Comment by pyrsmk** [comment]
Just pushed a new release, tell me if anything's going wrong ;)

**Comment by message** [comment]
Thanks, I will check tomorrow

**Comment by pyrsmk** [comment]
So, is it working?

**Comment by message** [comment]
yeah :) forgot to reply, thanks

**Comment by pyrsmk** [comment]
Great!
