### ISSUE TITLE
Dependencies not installed

### ISSUE THREAD

**Issue by willdady** [pyrsmk/qwest#70]
Latest version fails to install properly. Specifically `pinkySwear is not defined`. Presumably this is because it's listed as a devDependency and not a 'normal' dependency in the package.json file.

**Comment by darkyen** [comment]
+1

**Comment by pyrsmk** [comment]
Dependencies are installed but only for building. Do you use `src/qwest.js` or `qwest.min.js`?

**Comment by darkyen** [comment]
That will require doing `require("quest/quest.min.js");` instead of `require('qwest')`;

**Comment by willdady** [comment]
@pyrsmk Yes I was simply importing it using `require('qwest')`. The **non-minified** version should not have it's dependencies baked-in, rather they should be declared as dependencies in the package.json and imported using `require()`. What if my project already has dependencies on pinkyswear and/or jquery-param? I don't want to have these included in my project twice.

**Comment by pyrsmk** [comment]
I agree. In fact, at first I had requires in the source file. But browserify creates a context and then qwest can't be registered into `window`. That's why my gulpfile concatenates dependencies directly.

**Comment by raphaelparent** [comment]
Is this fixed? Because I still get the inital error `pinkySwear is not defined`.

**Comment by pyrsmk** [comment]
It should be fixed. Have you installed the latest version?

**Comment by raphaelparent** [comment]
Yes, 2.0.2 isn't it?

**Comment by pyrsmk** [comment]
Yes. I don't understand what's going on...

**Comment by raphaelparent** [comment]
I even reinstalled all my modules to make sure I had the good version.

**Comment by pyrsmk** [comment]
I have just tested it in one of my web projects. I have installed 2.0.2 via NPM, browserified the whole thing and I get the right qwest object returned. I'm making a simple `require('qwest')`.

What is your browser environment? What libraries and build system are you using?

**Comment by raphaelparent** [comment]
I'm using chrome. Besides qwest I use pagejs, vuejs and rasterizehtml. They work all of them. Browserify goes through the whole thing without error but it logs the initial statement.

**Comment by jkytomak** [comment]
2.0.2 not working for us either.
Project (still using older version);
https://github.com/opetushallitus/valtionavustus

**Comment by pyrsmk** [comment]
I identified the problem. When browserify is building the package it wraps completely the libraries and they're registering themselves with require and not in `window`. I think I should create one library for the browser and another for NPM.

**Comment by pyrsmk** [comment]
That should be fixed now with the last release. Reopen the issue if the problem persists ;)
