### ISSUE TITLE
Development/full version of qwest should work with full versions of dependencies

### ISSUE THREAD

**Issue by shwoodard** [pyrsmk/qwest#77]
IMHO, if I have amd config,

``` js
require.config({
  baseUrl: '/script',
  ...
  paths: {
      ...
      'qwest': ['lib/qwest'],
      'pinkyswear': ['lib/pinkyswear'],
      'jquery-param': ['lib/jquery-param']
  },
  ...
  shim: {
    ...
    'pinkyswear': {
      exports: 'pinkySwear'
    },
    'qwest': {
      deps: ['jquery-param', 'pinkyswear']
    }
  }
});
```

and the paths point to the full versions of the files, the library should work without requiring a build.

Actual:

```
Uncaught ReferenceError: PINKYSWEAR is not defined
```

**Comment by shwoodard** [comment]
UPDATE

Even switching for the built version I cannot get qwest to work with requirejs.  I'm using the above config.

```js
define(['qwest'), function(ajax) { console.log(ajax.post); /*undefined*/ })
```

Is there any documented setup for qwest and amd/requirejs?

**Comment by pyrsmk** [comment]
Thanks fort reporting, I'll investigate that ASAP

**Comment by pyrsmk** [comment]
I don't use RequireJS so I need some explanations on how you're using it. How are you using qwest? Do you pick the source file on the repo? Or installing it with NPM?

The minified version, at the root, is for the browser directly, all dependencies are included and qwest is referenced in `window`.
The NPM version (available with `require('qwest')` and existing in the `build/` directory), imports `pinkyswear` and `jquery-param` by itself.
The qwest source file should never be used.

Can you enumerate me your needs for RequireJS then I can see if I can create a specific build for it? Are you importing directly qwest via a package manager? Or are you composing your build by picking the files you're needing?

**Comment by jtenner** [comment]
@pyrsmk You can use the following browserify command to work with `require.js`

```
browserify -s qwest index.js > qwest.js
```

I am unable to submit a pull request at this moment, but that should give you what you need to fix this problem.

**Comment by pyrsmk** [comment]
Sorry for the late! I'm now working on better building system for qwest, based on @jtenner 's comment. I just don't really know how to do this without breaking things in user updates. I'd created an UMD branch, but it won't be available on NPM... So it seems I must push the changes on the master branch... But before doing anything crazy, is anyone have a better solution to test this?

**Comment by pyrsmk** [comment]
I've just pushed the new build process on the UMD branch.

There's a `qwest.min.js` that is the minified source file, and a `qwest.standalone.min.js` that is bundled with its dependencies and should work in the browser.
I'm not quite sure, but the `qwest.min.js` can only work on Node.js, isn't it?

@jtenner : if you have time for this, can you verify if all seems ok to you?

**Comment by pyrsmk** [comment]
Ok... I'm making the tests, there will be only one file : `qwest.min.js`. It should work with any environment. I'm also working on an implementation for web workers. Stay in touch.

**Comment by jtenner** [comment]
@pyrsmk making a standalone build should work perfectly in every environment.  Common.js, UMD, and browser.

Cheers,
-Josh

**Comment by pyrsmk** [comment]
Should be fixed now, reopen if needed

**Comment by tm57** [comment]
what's about support for bower too?

**Comment by pyrsmk** [comment]
I don't really understand your question, because qwest is already supported in bower.

**Comment by tm57** [comment]
I meant, installing the library using bower and then using requirejs to fetch the code, it does not register. It;s undefined.

I had to use the `npm` version in the end and it works. Will be good to have it work in bower too

**Comment by pyrsmk** [comment]
Hum... It is weird... The main file in `package.json` and `bower.json` is the same. I assume that the issue comes from the dependencies, which are defined in `package.json` but not in `bower.json` because PinkySwear is not available on bower.

If my assumption is right, we'll need to wait for the future v5 version (PinkySwear will be dropped in favor of better/stronger implementation).

**Comment by pyrsmk** [comment]
@tm57 : I'm not used to RequireJS but did you take the good qwest version? Because the one located in `src/` is not meant to be used as is, you should take the `qwest.js` version at the root of the project.
