### ISSUE TITLE
It's not possible to use it in Web Worker

### ISSUE THREAD

**Issue by VanDalkvist** [pyrsmk/qwest#78]
It's not possible to use it in Web Worker because you use window object which is not allowed in workers.

**Comment by pyrsmk** [comment]
I'm currently working on a way to integrate qwest better with any environment, on the UMD branch. Moreover, I don't know anything for the moment on web workers. I'll take a look ASAP ;)

**Comment by pyrsmk** [comment]
Ok, good news, it should be possible to have qwest working in web workers with the future release.

**Comment by VanDalkvist** [comment]
@pyrsmk Great, thank you for fast reply :)

**Comment by pyrsmk** [comment]
Should be fixed now, reopen if needed

**Comment by DinkoMiletic** [comment]
Hello,

Using latest version from bower. It looks like window is used again.

`Uncaught ReferenceError: window is not defined`

**Comment by pyrsmk** [comment]
Ah, sorry! I'll push a new release tomorrow ;)

**Comment by pyrsmk** [comment]
@DinkoMiletic I have updated to `4.4.4` with a change for Web Workers. Can you tell me if it's still working, if you have time?
