### ISSUE TITLE
How can i break the executing `then` or `catch`?

### ISSUE THREAD

**Issue by LestaD** [pyrsmk/qwest#83]
I have code:

```js
// requester.js

function get(url) {
  return Qwest.get(url).catch((xhr, e, resp) => {
    // here i need «filter» error
    // example:
    if (e.error == 400) {
      return true;
    }
    else {
      ErrorHandler.raise(xhr, e, resp, e.error); // my special error handler
      return false; // after `false` next `then` not be executed
      // or this.break() ?
    }
  });
}
```

```js
// account_action.js

function LoadAccount() {
  Requester.get('/account/')
  .then((x, acc) => {
   // save account here
  })
  .catch((x, err, r) => {
    // here i want catch only `400` errors
  });
}
```

> sorry for my English

**Comment by pyrsmk** [comment]
It seems it's a behavior that PinkySwear should handle... Your code doesn't work? What is blocking?

**Comment by LestaD** [comment]
@pyrsmk i want to stop execute in `requester.js` on `catch()`

**Comment by pyrsmk** [comment]
What do you mean by "stop" exactly?

**Comment by pyrsmk** [comment]
Ah, nevermind. I begin to understand what you're wanting.

**Comment by pyrsmk** [comment]
For the moment, you can't do it, but I'm watching for a way to do it. In fact, we need to override the configuration that qwest set on PinkySwear (which take care of promises).

**Comment by pyrsmk** [comment]
I've just updated the repository. You can, now, override promise methods by adding an option `pinkyswear` : 

```js
qwest.get(url, null, {
    pinkyswear: {
        catch: function() {
            // blah blah blah
        }
    }
});
```

Currently, pinkyswear methods are set like this : 

```js
pinky['catch'] = function(f) {
	return pinky.then(null, f);
};
pinky.complete = function(f) {
	return pinky.then(f, f);
};
```

Tell me if it's working as expected ;)

**Comment by LestaD** [comment]
I will test it. Thanks!!

**Comment by pyrsmk** [comment]
So... Working like a charm? :p

**Comment by LestaD** [comment]
I do that:

```js
export function requestGet(url, data, options) {
  return new Promise((resolve, reject) => {
    Qwest.get(url, data)
    .then((xhr, response) => resolve(response)).catch((xhr, response) => {
      if (response.error == 'Some error') return;
      reject(response)
    });
  });
}
```

**Comment by pyrsmk** [comment]
Ok, but is the option I added a few days ago working? Did you test it?

**Comment by pyrsmk** [comment]
I'll remove this functionnality since it's still experimental and the `4.0` will be out soon

**Comment by JemarJones** [comment]
So, that functionality is gone then? Is there a way to do it?

**Comment by JemarJones** [comment]
I think the issue should be reopened!

**Comment by pyrsmk** [comment]
I don't remember well what was really blocking here. The promises should work as expected by the [spec](https://promisesaplus.com). But the implementation of promises in qwest (handled by Pinkyswear) is not reliable enough and will be soon dropped for Zousan. I planned to completely rewrite qwest for the v5.

Anyway, long story short, if the requested behavior is handled by the promises spec, it should work. If not, it will when the v5 will be out.

**Comment by JemarJones** [comment]
How is it, in qwest, that you re-throw an error? So that the next catch can be called with the `(err, xhr, response)` signature?

**Comment by pyrsmk** [comment]
In qwest, I think it should look like this : 

```js
qwest(...).then(function(xhr, response) {
    // do stuff
}).catch(function(e, xhr, response) {
    throw new Error(e);
}).catch(function(e) {
    throw new Error(e);
});
```

The next catch can't have `(e, xhr, response)`, because the promise only returns one var. It's the same for `then` :

```js
qwest(...).then(function(xhr, response) {
    return 42;
}).then(function(var) {
    // prints 42
    console.log(var);
});
```
