### ISSUE TITLE
How can I use Qwest in node.js?

### ISSUE THREAD

**Issue by LestaD** [pyrsmk/qwest#85]

**Comment by pyrsmk** [comment]
I don't know, I don't use node.js. But it shouldn't work since qwest needs XMLHttpRequest and, tell me if I'm wrong, it is just shipped in the browser, isn't it?

**Comment by darkwebdev** [comment]
The problem is you can't use it with mocha, you have to use jasmine+browser or phantomJs or jsDom, cause now you need window.

**Comment by LestaD** [comment]
@darkwebdev i use `axios` instead `qwest`

**Comment by pyrsmk** [comment]
:+1:
