### ISSUE TITLE
Is it possible to set defaults for all requests?

### ISSUE THREAD

**Issue by basharov** [pyrsmk/qwest#88]
I want to make all requests default as `{dataType: 'json'}`. Is it possible?

**Comment by pyrsmk** [comment]
It's not possible, but I'll write a quick patch today so you'll can do it ;)

**Comment by basharov** [comment]
Thanks man!

**Comment by pyrsmk** [comment]
Just pushed a new version.

```js
qwest.setDefaultDataType('json');
```
