### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by pierot** [pyrsmk/qwest#91]
I'm struggling with making file uploads work.
I have this setup right now:

``` javascript
    qwest.post(
      url,
      object,
      {
        headers: {
          "Content-Type": "application/octet-stream"
        },
        responseType: "json",
        dataType: "formdata"
      }
    )
```

The `object` argument is a Javascript object with some fields and a File Object.
What other settings am I missing?

Thanks

**Comment by pyrsmk** [comment]
In my opinion, your `Content-Type` header is conflicting with the real type of the sent data. Please remove it and tell me if it works.

**Comment by pierot** [comment]
When removing the `Content-Type` header the `Request Payload` (as seen in Chrome) is still:
![8yvly2q_lhscu18jwtqdzo_e8svszfhoigrd1g28a_u](https://cloud.githubusercontent.com/assets/46622/11442670/9d55d97c-9517-11e5-975d-b902161e6126.png)

**Comment by pyrsmk** [comment]
What is the expected behavior? (sorry, I never use that)

**Comment by debian-sh** [comment]
@pierot maybe you need to create `var fd = new FormData();` append all fields + files and give the `FormData Object` as object to the post function in qwest.

**Comment by pierot** [comment]
@pyrsmk @debian-sh 
Sorry to not answer my own question after all; I forgot I had this ticket here.

This is the solution (@pyrsmk maybe add this to the docs?)
```javascript
    let formData = new FormData()
    formData.append(key, value)

    qwest.post(
      url,
      formData,
      {
        responseType: "json",
        dataType: "formdata"
      }
    )
    .then((xhr, response) => {
      
    })
    .catch((xhr, response, e) => {
      
    })
```
