### ISSUE TITLE
XDomainRequest requests being aborted on IE9

### ISSUE THREAD

**Issue by eb-drocha** [pyrsmk/qwest#93]
I've detected that when doing croos-domain ajax requests on IE9, which uses the XDomainRequest object, the request is aborted.
Following the article on http://cypressnorth.com/programming/internet-explorer-aborting-ajax-requests-fixed/, I came up with a solution for this: there's the need to define the methods "onprogress" and "ontimeout" of XDomainRequest with empty functions.

So, on line 822 of src/qwest.js, Ive added them
```javascript
if(xdr) {
    xhr.onprogress = function () {}; // added
    xhr.ontimeout = function () {};    // added
    setTimeout(function(){ // https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest
        xhr.send(method!='GET'?data:null);
    },0);
}
```

and it started working.
I have not rights on this repository to push a branch with this correction and the respective pull request.

**Comment by pyrsmk** [comment]
Thanks a lot for the fix. I'm fixing it ;)

**Comment by pyrsmk** [comment]
The fixed has just been pushed

**Comment by eb-drocha** [comment]
Thank you very much!
