### ISSUE TITLE
Global catch?

### ISSUE THREAD

**Issue by phillip-haydon** [pyrsmk/qwest#95]
Sorry I couldn't find this in doco anywhere. 

Is there support for a global catch/error? Basically I want to say:

```
qwest.catch(function(xhr, response, e) {
   if (xhr.status === 401) { showLogin(); }
});
```

Something like that, which applied to every request.

**Comment by pyrsmk** [comment]
I thin it's impossible to set a global catch with promises, by design. You should create your own global function to create your requests like : 

```js
function sendRequest(url, data, options, callback) {
    qwest.get(url, data, options)
             .then(callback)
             .catch(function(xhr, response, e) {
                  if (xhr.status === 401) { showLogin(); }
             });
}
```

**Comment by phillip-haydon** [comment]
Ok, no worries. Figured I should ask. :)

Thanks.

**Comment by pyrsmk** [comment]
Np ;)
